# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

1. List of the first 15 even numbers that are not divisible by 6
"""

l = []
x = 10
count = 0
while True:
  if x % 6 != 0 and x % 2 == 0:
    count = count + 1
    l.append(x)
  if count == 15:
    break
  x = x + 1

print(l)

"""2. Write a function to Check whether given two string is anagram or not"""

def anagram(str1,str2):
  if(sorted(str1) == sorted(str2)):
    print("\tString are anagram")
  else:
    print("\tString are not anagram")
str1 = input("\t First String: ")
str2 = input("\tSecond String: ")
anagram(str1,str2)

"""3. Define a class which has at least two methods: getString: to get a string from console input printString: to print the string in upper case. Also please include simple test function to test the class methods."""

class myclass():
      def get_str(self):
          self.str1 = input()
  
      def print_str(self):
          print(self.str1.upper())
  
  str1 = myclass()
  str1.get_str()
  str1.print_str()